logging.level:
  tgmentionsbot: DEBUG

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 30000 # 30 seconds
      idle-timeout: 600000  # 10 minutes
      max-lifetime: 1800000 # 30 minutes

tgmentionsbot:
  bot-username: ${BOT_USERNAME:}
  bot-token: ${BOT_TOKEN:}
